spring:
  application:
    name: crud-api
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-self-references: false

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      # type: TRACE

server:
  port: 8080
  servlet:
    context-path: /api


